extern const GeoLayout plank_geo[];
extern Lights1 plank_f3d_material_lights;
extern u8 plank_woodPlatform_ci4[];
extern u8 plank_woodPlatform_ci4_pal_rgba16[];
extern Vtx plank_Plank_mesh_layer_1_vtx_cull[8];
extern Vtx plank_Plank_mesh_layer_1_vtx_0[20];
extern Gfx plank_Plank_mesh_layer_1_tri_0[];
extern Gfx mat_plank_f3d_material[];
extern Gfx mat_revert_plank_f3d_material[];
extern Gfx plank_Plank_mesh_layer_1[];
extern Gfx plank_material_revert_render_settings[];
