extern const GeoLayout castle_grounds_area_1_geo[];
extern const GeoLayout castle_grounds_area_1[];
extern const Collision castle_grounds_area_1_collision[];
extern const MacroObject castle_grounds_area_1_macro_objs[];
extern u8 castle_grounds_dl_Box_i4[];
extern u8 castle_grounds_dl_wood2_ci4[];
extern u8 castle_grounds_dl_wood2_ci4_pal_rgba16[];
extern u8 castle_grounds_dl_ki_02_ci4[];
extern u8 castle_grounds_dl_ki_02_ci4_pal_rgba16[];
extern u8 castle_grounds_dl_EdenGrassI4_i4[];
extern Vtx castle_grounds_dl_Cube_mesh_layer_1_vtx_cull[8];
extern Vtx castle_grounds_dl_Cube_mesh_layer_1_vtx_0[24];
extern Gfx castle_grounds_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx castle_grounds_dl_Fireplace_mesh_layer_1_vtx_cull[8];
extern Vtx castle_grounds_dl_Fireplace_mesh_layer_1_vtx_0[84];
extern Gfx castle_grounds_dl_Fireplace_mesh_layer_1_tri_0[];
extern Vtx castle_grounds_dl_Fireplace_mesh_layer_1_vtx_1[58];
extern Gfx castle_grounds_dl_Fireplace_mesh_layer_1_tri_1[];
extern Vtx castle_grounds_dl_FireplaceLOD_mesh_layer_1_vtx_cull[8];
extern Vtx castle_grounds_dl_FireplaceLOD_mesh_layer_1_vtx_0[25];
extern Gfx castle_grounds_dl_FireplaceLOD_mesh_layer_1_tri_0[];
extern Vtx castle_grounds_dl_FireplaceLOD_mesh_layer_1_vtx_1[35];
extern Gfx castle_grounds_dl_FireplaceLOD_mesh_layer_1_tri_1[];
extern Vtx castle_grounds_dl_Plane_mesh_layer_1_vtx_cull[8];
extern Vtx castle_grounds_dl_Plane_mesh_layer_1_vtx_0[138];
extern Gfx castle_grounds_dl_Plane_mesh_layer_1_tri_0[];
extern Gfx mat_castle_grounds_dl_f3d_material_001_layer1[];
extern Gfx mat_revert_castle_grounds_dl_f3d_material_001_layer1[];
extern Gfx mat_castle_grounds_dl_Wood2[];
extern Gfx mat_revert_castle_grounds_dl_Wood2[];
extern Gfx mat_castle_grounds_dl_Wood[];
extern Gfx mat_revert_castle_grounds_dl_Wood[];
extern Gfx mat_castle_grounds_dl_Terrain_layer1[];
extern Gfx mat_revert_castle_grounds_dl_Terrain_layer1[];
extern Gfx castle_grounds_dl_Cube_mesh_layer_1[];
extern Gfx castle_grounds_dl_Fireplace_mesh_layer_1[];
extern Gfx castle_grounds_dl_FireplaceLOD_mesh_layer_1[];
extern Gfx castle_grounds_dl_Plane_mesh_layer_1[];
extern Gfx castle_grounds_dl_material_revert_render_settings[];
