extern void scroll_castle_grounds_dl_000AAALake_mesh_layer_5_vtx_0();
extern void scroll_castle_grounds_dl_AAARiver_mesh_layer_5_vtx_0();
extern void scroll_castle_grounds_dl_000AAALake_001_mesh_layer_5_vtx_0();
extern void scroll_castle_grounds_dl_AAARiver_001_mesh_layer_5_vtx_0();
extern void scroll_castle_grounds();
