extern const GeoLayout rock_boulder_geo[];
extern u8 rock_boulder_wood_rock_ci8[];
extern u8 rock_boulder_wood_rock_ci8_pal_rgba16[];
extern Vtx rock_boulder_Boulder_mesh_layer_1_vtx_cull[8];
extern Vtx rock_boulder_Boulder_mesh_layer_1_vtx_0[93];
extern Gfx rock_boulder_Boulder_mesh_layer_1_tri_0[];
extern Gfx mat_rock_boulder_Rock[];
extern Gfx mat_revert_rock_boulder_Rock[];
extern Gfx rock_boulder_Boulder_mesh_layer_1[];
extern Gfx rock_boulder_material_revert_render_settings[];
