extern const GeoLayout bob_area_1_geo[];
extern const GeoLayout bob_area_1[];
extern const Collision bob_area_1_collision[];
extern const MacroObject bob_area_1_macro_objs[];
extern u8 bob_dl_ss_rock_floor_ci4_ci4[];
extern u8 bob_dl_ss_rock_floor_ci4_ci4_pal_rgba16[];
extern u8 bob_dl_MARIOKART64_5E32ECAB_0_2_all_i8[];
extern Vtx bob_dl_Plane_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Plane_mesh_layer_1_vtx_0[16];
extern Gfx bob_dl_Plane_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Plane_mesh_layer_1_vtx_1[4];
extern Gfx bob_dl_Plane_mesh_layer_1_tri_1[];
extern Vtx bob_dl_Plane_mesh_layer_1_vtx_2[8];
extern Gfx bob_dl_Plane_mesh_layer_1_tri_2[];
extern Gfx mat_bob_dl_f3d_material_001[];
extern Gfx mat_revert_bob_dl_f3d_material_001[];
extern Gfx mat_bob_dl_Road[];
extern Gfx mat_bob_dl_f3d_material[];
extern Gfx bob_dl_Plane_mesh_layer_1[];
extern Gfx bob_dl_material_revert_render_settings[];
