extern const GeoLayout wood_platform_geo[];
extern u8 wood_platform_woodPlatform_ci4[];
extern u8 wood_platform_woodPlatform_ci4_pal_rgba16[];
extern Vtx wood_platform_Cube_mesh_layer_1_vtx_cull[8];
extern Vtx wood_platform_Cube_mesh_layer_1_vtx_0[24];
extern Gfx wood_platform_Cube_mesh_layer_1_tri_0[];
extern Gfx mat_wood_platform_Platform[];
extern Gfx mat_revert_wood_platform_Platform[];
extern Gfx wood_platform_Cube_mesh_layer_1[];
extern Gfx wood_platform_material_revert_render_settings[];
