extern const GeoLayout wf_area_1_geo[];
extern const GeoLayout wf_area_1[];
extern const Collision wf_area_1_collision[];
extern const MacroObject wf_area_1_macro_objs[];
extern u8 wf_dl_regular_grass_ci4_ci4[];
extern u8 wf_dl_regular_grass_ci4_ci4_pal_rgba16[];
extern u8 wf_dl_GroundBaseRock02_alb_RGBA16_ci8[];
extern u8 wf_dl_GroundBaseRock02_alb_RGBA16_ci8_pal_rgba16[];
extern u8 wf_dl_Glover_5A3FAD3C_0_0_FC6C0B44_ciByRGBA_ci4_ci4[];
extern u8 wf_dl_Glover_5A3FAD3C_0_0_FC6C0B44_ciByRGBA_ci4_ci4_pal_rgba16[];
extern u8 wf_dl_GMPE01_40f584e2_14_ci4_ci4[];
extern u8 wf_dl_GMPE01_40f584e2_14_ci4_ci4_pal_rgba16[];
extern Vtx wf_dl_Cube_mesh_layer_1_vtx_cull[8];
extern Vtx wf_dl_Cube_mesh_layer_1_vtx_0[10];
extern Gfx wf_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Cube_mesh_layer_1_vtx_1[203];
extern Gfx wf_dl_Cube_mesh_layer_1_tri_1[];
extern Vtx wf_dl_Cube_mesh_layer_1_vtx_2[24];
extern Gfx wf_dl_Cube_mesh_layer_1_tri_2[];
extern Vtx wf_dl_Cube_mesh_layer_1_vtx_3[9];
extern Gfx wf_dl_Cube_mesh_layer_1_tri_3[];
extern Vtx wf_dl_Cube_mesh_layer_1_vtx_4[24];
extern Gfx wf_dl_Cube_mesh_layer_1_tri_4[];
extern Vtx wf_dl_Cube_001_mesh_layer_1_vtx_cull[8];
extern Vtx wf_dl_Cube_001_mesh_layer_1_vtx_0[32];
extern Gfx wf_dl_Cube_001_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Cube_001_mesh_layer_1_vtx_1[27];
extern Gfx wf_dl_Cube_001_mesh_layer_1_tri_1[];
extern Vtx wf_dl_Cube_001_mesh_layer_5_vtx_cull[8];
extern Vtx wf_dl_Cube_001_mesh_layer_5_vtx_0[12];
extern Gfx wf_dl_Cube_001_mesh_layer_5_tri_0[];
extern Gfx mat_wf_dl_grass[];
extern Gfx mat_revert_wf_dl_grass[];
extern Gfx mat_wf_dl_Rock[];
extern Gfx mat_revert_wf_dl_Rock[];
extern Gfx mat_wf_dl_DirtTopDown[];
extern Gfx mat_revert_wf_dl_DirtTopDown[];
extern Gfx mat_wf_dl_DirtBehind[];
extern Gfx mat_revert_wf_dl_DirtBehind[];
extern Gfx mat_wf_dl_DirtNormalCamera[];
extern Gfx mat_revert_wf_dl_DirtNormalCamera[];
extern Gfx mat_wf_dl_Water[];
extern Gfx mat_revert_wf_dl_Water[];
extern Gfx wf_dl_Cube_mesh_layer_1[];
extern Gfx wf_dl_Cube_001_mesh_layer_1[];
extern Gfx wf_dl_Cube_001_mesh_layer_5[];
extern Gfx wf_dl_material_revert_render_settings[];
