extern const GeoLayout stool_geo[];
extern u8 stool_StoolWood_ci4[];
extern u8 stool_StoolWood_ci4_pal_rgba16[];
extern Vtx stool_StoolVisual_mesh_layer_1_vtx_cull[8];
extern Vtx stool_StoolVisual_mesh_layer_1_vtx_0[80];
extern Gfx stool_StoolVisual_mesh_layer_1_tri_0[];
extern Gfx mat_stool_Wood[];
extern Gfx mat_revert_stool_Wood[];
extern Gfx stool_StoolVisual_mesh_layer_1[];
extern Gfx stool_material_revert_render_settings[];
